DEBUG = True

BONUSES_API_PREFIX = '/api/v1'

MONGO_URI = 'mongodb://127.0.0.1:27017'

SECRET_KEY = 'SECRET KEY'

JWT_AUTH_URL_RULE = BONUSES_API_PREFIX + '/auth'

BRUTEFORCE_WINDOW = 60
BRUTEFORCE_THRESHOLD = 10
BRUTEFORCE_LAG = 1
